name: Cypress-CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
       run:
         working-directory: ./cypress
    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './cypress/package-lock.json'
#    - uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#        cache-dependency-path: './cypress/package-lock.json'
    - name: Install dependencies
      run: npm install
      working-directory: cypress

    - name: Run Cypress
      run: npm run cr
      working-directory: cypress