name: Cypress-CI Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
#on: push
#    paths:
#      - 'cypress/**'

jobs:
  # This workflow contains a single job called "greet"
  cypressJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #- uses: cypress/
    - name: Install dependencies
      run: npm install
      working-directory: cypress

    - name: Run Cypress
      run: npm run cr
      working-directory: cypress